apiVersion: v1
kind: Service
metadata:
  name: argo-server-external
  namespace: argo
spec:
  type: LoadBalancer
  selector:
    app: argo-server
  ports:
    - protocol: TCP
      port: 2746 
      targetPort: 2746
